In [3]:
def read_episode(f):
    episode = []
    epLen = int(f.readline())
    for st in range(epLen):
        ln = f.readline()[:-1]
        vals = ln.split(",")
        vals = {"s": int(vals[0]), "a": int(vals[1]), "r": float(vals[2]), "prob": float(vals[3])}
        #print(vals)
        episode.append(vals)
    return episode
def read_data(dat_fl):
    ret = []
    with open(dat_fl, "r") as f:
        eps = int(f.readline())
        for ep in range(eps):
            episode = read_episode(f)
            ret.append(episode)
    return ret


dat_fl = "data.csv"
dat = read_data("data.csv")

In [20]:
print(len(dat))
print(len(dat[0]))
print(len(dat[-1]))
print(dat[0][0])

1000000
68
13
{'s': 17, 'a': 2, 'r': 1.0, 'prob': 0.125}


In [17]:
print(reward)

[[0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         5.50848858 0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         5.50343564]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         1.         1.        ]]


In [19]:
print(psas[0, :, :])

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
import pickle as pkl
with open("dat.pkl", "wb") as f:
    pkl.dump(dat, f)

In [22]:
with open("dat.pkl", "rb") as f:
    dat = pkl.load(f)

In [4]:
import numpy as np

def make_model():
    psas = np.zeros((18, 4, 18))
    reward = np.zeros((18, 4))
    reward_count = np.zeros((18, 4))
    for episode in dat:
        for idx, val in enumerate(episode):
            s = val['s']
            a = val['a']
            r = val['r']
            reward[s, a] += r
            reward_count[s, a] += 1
            if idx < len(episode) - 1:
                sp = episode[idx + 1]['s']
                psas[s, a, sp] += 1
    reward_count = np.maximum(reward_count, 1)
    print(reward_count)
    reward /= reward_count
    for idx1 in range(psas.shape[0]):
        for idx2 in range(psas.shape[1]):
            sm = np.sum(psas[idx1, idx2, :])
            if sm > 0:
                psas[idx1, idx2, :] /= sm
            else:
                psas[idx1, idx2, :] = 1.0/18
    #print(psas)
    return (reward, psas)

(reward, psas) = make_model()
    


[[1.857325e+06 1.854843e+06 1.855831e+06 1.857339e+06]
 [1.359353e+06 1.355745e+06 1.358209e+06 1.355663e+06]
 [1.071476e+06 1.072048e+06 1.069895e+06 1.070603e+06]
 [9.299510e+05 9.277210e+05 9.283250e+05 9.282430e+05]
 [1.353973e+06 1.357334e+06 1.355931e+06 1.356830e+06]
 [1.142383e+06 1.142122e+06 1.142295e+06 1.144048e+06]
 [9.285580e+05 9.293670e+05 9.287120e+05 9.277650e+05]
 [7.854430e+05 7.847580e+05 7.839520e+05 7.833410e+05]
 [1.070999e+06 1.072994e+06 1.071378e+06 1.070747e+06]
 [9.295610e+05 9.278360e+05 9.276120e+05 9.284670e+05]
 [7.143540e+05 7.146070e+05 7.143720e+05 7.137480e+05]
 [4.986670e+05 5.009670e+05 4.988720e+05 4.993640e+05]
 [9.297940e+05 9.272980e+05 9.285790e+05 9.294180e+05]
 [7.862350e+05 7.859900e+05 7.862180e+05 7.848450e+05]
 [5.003750e+05 5.004630e+05 5.000440e+05 4.990330e+05]
 [1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00]
 [2.492610e+05 2.501860e+05 2.508440e+05 2.497090e+05]
 [3.756160e+05 3.744300e+05 1.248980e+05 1.250560e+05]]


In [6]:
import time
def scan_time(data_file_path):
    start_time = time.time()
    with open(data_file_path, 'r') as f:
        N = int(f.readline())
        for k in range(N):
            L = int(f.readline())
            for i in range(L):
                line = str(f.readline()).rstrip().split(',')
                s_a_r_pi = tuple([int(e) if i <=2 else float(e) for i, e in enumerate(line)])
            if k%100000 == 0:
                print("Processed ", k+1)
    end_time = time.time()
    print(end_time-start_time, " -> total eclipsed time")
data_file_path = 'data.csv'
scan_time(data_file_path)

Processed  1
Processed  100001
Processed  200001
Processed  300001
Processed  400001
Processed  500001
Processed  600001
Processed  700001
Processed  800001
Processed  900001
142.60713005065918  -> total eclipsed time
